### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by ErikMcClure** [ErikMcClure/PonyClicker#82]
Predictably, trying to make a graphically intensive game in HTML is catastrophically bad for performance. As much as I like using newfangled CSS stuff, I suggest moving everything in the pony field to HTML canvas rendering, which is better optimized and doesn't rely on DOM manipulation to achieve things.

In the short term, pinkie GIFs are apparently extremely expensive on some machines, for some reason, and there should be an option to replace them with a static image.

A nice short term solution is to simply replace all SVGs with canvas elements that have an SVG pre-rendered on them.

**Comment by blackhole12** [comment]
The canvas caching part of this was implemented in v1.0.4
