### ISSUE TITLE
Tooltip behavior with upgrades

### ISSUE THREAD

**Issue by 3plus4i** [ErikMcClure/PonyClicker#95]
Um, I'm not even sure how to describe this error properly (with my somewhat limited English). The tooltips of upgrades are somehow shifted. When you move to the right side/bottom of the button, the text of the tooltip changes too quickly to the one of the next upgrade. The further right/down the upgrade is positioned, the bigger the offset. This can ad up to almost half of the whole button.

Oh, clicking with the wrong text showing still gets you the correct upgrade.

**Comment by blackhole12** [comment]
I have actually noticed this but haven't gotten around to fixing it. I
suspect the height offset is off by a pixel.

**Comment by 3plus4i** [comment]
Just discovered, that it works correctly in the menu, with the already bought upgrades. Can't the styling simply be transferred?

**Comment by blackhole12** [comment]
Those actually use two completely different styles because the behavior is different.

**Comment by 3plus4i** [comment]
Hm, I already suspected my assumption to be too naive ...
